### ISSUE TITLE
Email notifications are no longer working in v.17

### ISSUE THREAD

**Issue by alexwojtowicz** [umbraco/Umbraco.Workflow.Issues#124]
I am no longer receiving email notifications after upgrading to v.17.0.1 (previously was working in v.16.0.6).

**Umbraco CMS: 17.0.2**
**Workflow: 17.0.1**

### Settings:

<img width="2560" height="911" alt="Image" src="https://github.com/user-attachments/assets/f5e4f6ba-84da-4c8d-a313-3e4cfa7edc5b" />

<img width="2560" height="911" alt="Image" src="https://github.com/user-attachments/assets/669911f1-4140-4f29-9bac-6ee58ed97bb2" />

<img width="2560" height="911" alt="Image" src="https://github.com/user-attachments/assets/bf3acc16-150d-4142-8f07-db44f1b1619b" />

### Document approval workflow:

<img width="2560" height="911" alt="Image" src="https://github.com/user-attachments/assets/4297c7b2-125d-4d03-8116-70e503601025" />

### Approval group:

<img width="2560" height="911" alt="Image" src="https://github.com/user-attachments/assets/d6931bd6-4832-4b9f-9f3f-dfa52d6f2137" />

<img width="2560" height="911" alt="Image" src="https://github.com/user-attachments/assets/9947d121-bd2c-46ff-9998-fc0eca323672" />

I have not modified any of the default templates. I am not observing any issues in the logs. We also have Umbraco Forms installed, so I tested sending emails in the Umbraco Forms submission workflows, and those are sending. We are using Mailgun for SMTP, and after checking the Mailgun logs, we have confirmed that there is no record of emails being sent as part of the Umbraco Workflow workflow.

Reproduction
------------

1) You will need to create two users Y and Z.
2) Configure the Workflow settings as shown in the screenshots above.
3) Configure an approval group A and add user Y.
4) Configure a document approval workflow (single-stage) using approval group A on a node X
5) Sign into Umbraco as user Z and submit approval for changes on node X (make sure to add comments)
6) Sign out and log into user Y. On the dashboard, you will see a task for a pending approval.
7) As user Y, approve the workflow.

I have the settings configured such that when a workflow approval request is submitted, the users in the approval group should be notified. So, on step 5, user Y should have been sent an email since they are in approval group A, but no email was received. On step 7, after user Y approves the workflow, since it is configured to send notifications to the content author and the approval group, users Y and Z should have gotten an email, but neither users received it.

**Comment by nathanwoulfe** [comment]
@alexwojtowicz pretty sure this is due to the RuntimeCompilation changes in 17... Working on a fix, will hopefully have it patched this week.

**Comment by nathanwoulfe** [comment]
@alexwojtowicz this should be resolved in 17.0.2 - email template are no longer compiled from embedded resources, instead are copied to disk on first-send (if the file doesn't already exist), and compiled using the Razor view engine.

**Comment by alexwojtowicz** [comment]
@nathanwoulfe This is still an issue in 17.0.2. I also tried installing the templates onto disk and recompiling. Even after doing so and initiating another workflow, I am still not receiving notifications.
